# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
  #- command: docker build -t node-express-api:latest .
  #- command: docker run --name user-api -d -p 3000:3000 node-express-api:latest
  - init: npm install express
  - command: node index.js

#image:
#  file: .gitpod.Dockerfile

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
